lists:
  - name: evidence_group
    items:
      - text: Passport or travel document
        value: passport
      - text: Driving licence or card
        value: driving_licence
      - text: Identity card
        value: id_card
      - text: Account, bill or statement
        value: account
      - text: Certificate
        value: certificate
      - text: Document issued by a local authority
        value: local_authority_doc
      - text: Other evidence not listed
        value: other

  - name: evidence_type
    items:
      - text: UK passport
        value: passport_uk
        short_name: UK passport
        strength: 4
      - text: A passport that meets the International Civil Aviation Organisation (ICAO) specifications for machine-readable travel documents (9303)
        value: passport_icao
        short_name: passport
        strength: 3
      - text: biometric passports that meet the ICAO specifications for e-passports
        value: passport_biometric
        short_name: biometric passport
        strength: 4
      - text: US passport card
        value: passport_us
        strength: 3
      - text: Home Office travel document
        value: passport_document
        strength: 2

      - text: UK photocard driving licence
        value: driving_licence_uk_photocard
        short_name: UK driving licence
        strength: 3
      - text: EU or EEA driving licence
        value: driving_licence_eea
        strength: 3
      - text: Digital tachograph driver smart card
        value: driving_licence_tachograph
        short_name: tachograph smart card
        strength: 3

      - text: armed forces identity card
        value: id_card_forces
        strength: 3
      - text: biometric residence permit
        value: id_card_residence_permit
        strength: 4
      - text: An identity card from an EU or European Economic Area (EEA) country that meets the Council Regulation (EC) No 2252/2004 standards
        short_name: EU or EEA identity card
        value: id_card_eea_non_biometric
        strength: 3
      - text: An identity card from an EU or EEA country that meets the Council Regulation (EC) No 2252/2004 standards and contains biometric information
        value: id_card_eea_biometric
        short_name: EU or EEA biometric identity card
        strength: 4
      - text: Proof of age card recognised under the Proof of Age Standards Scheme (PASS)
        value: id_card_proof_of_age_no_reference_number
        short_name: proof of age card
        strength: 2
      - text: Proof of age card with a Proof of Age Standards Scheme (PASS) with a reference number
        value: id_card_proof_of_age_with_reference_number
        short_name: proof of age card (with reference number)
        strength: 3
      - text: Northern Ireland electoral identity card
        value: id_card_ni_electoral
        short_name: NI electoral identity card
        strength: 3

      - text: gas or electric bill
        value: account_utility_bill
        strength: 2
      - text: student loan account
        value: account_student_loan
        strength: 3
      - text: bank, building society or credit union current account
        value: account_bank
        strength: 3
      - text: credit account
        value: account_credit
        strength: 3
      - text: mortgage account
        value: account_mortgage
        strength: 3
      - text: secured loan account
        value: account_loan
        strength: 3
      - text: building, contents or vehicle insurance
        value: account_insurance
        short_name: insurance document
        strength: 2
      - text: rental or purchase agreement for a residential property
        value: account_rental
        short_name: rental or purchase agreement
        strength: 2

      - text: birth or adoption certificate
        value: certificate_birth
        strength: 2
      - text: marriage or civil partnership certificate
        value: certificate_marriage
        strength: 2
      - text: education certificate from a regulated and recognised educational institution
        value: certificate_education
        short_name: education certificate
        strength: 2
      - text: firearm certificate
        value: certificate_firearm
        strength: 2

      - text: older personâ€™s bus pass
        value: local_authority_doc_bus_pass
        short_name: bus pass
        strength: 2
      - text: freedom pass
        value: local_authority_doc_freedom_pass
        strength: 2
      - text: letter from a local authority
        value: local_authority_doc_letter
        strength: 1

  - name: official_templates_update_frequency
    items:
      - text: Every year
        value: every_year
      - text: Every 3 years
        value: every_3_years
      - text: The templates are never updated
        value: never

  - name: visible_features
    items:
      - text: Designs printed using intaglio (raised) ink
        value: printed_using_intaglio
      - text: Designs that have been laser etched
        value: laser_etched
      - text: Watermarks
        value: watermarks
      - text: Security fibres
        value: security_fibres
      - text: Secondary background ('ghost') images
        value: secondary_background

  - name: visible_features_equipment
    items:
      - text: A magnification tool (such as a magnifier)
        value: magnification_tool
      - text: A low angle ('oblique') light
        value: low_angle_light
      - text: Another piece of equipment that can be used to identify forged or counterfeit documents
        value: other_equipment
      - text: A non-specialist light source, like natural sunlight, indoor lights or a desk lamp
        value: non_specialist_light_source

  - name: uv_ir_features
    items:
      - text: The paper the document is printed on
        value: paper_printed_on
      - text: The layout and design of the document
        value: layout_of_document
      - text: Any fluorescent features (such as fluorescent inks or fibres)
        value: fluorescent_features

  - name: crypto_features
    items:
      - text: Check the evidence has not expired
        value: not_expired
      - text: Check the digital signature is correct
        value: digital_signature
      - text: Check the signing key belongs to the organisation that issued the evidence
        value: organisation_signing_key
      - text: Check the signing key is correct for that type of evidence
        value: evidence_signing_key
      - text: Check the signing key has not been revoked (this could happen if the security features have been compromised)
        value: revoked_signing_key
      - text: You do not check any of these things
        value: dont_check